<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sovy 404 Gutenverse Hero', 'sovy' ),
	'categories' => array( 'sovy-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1295"},"height":{"Desktop":{"unit":"vh","point":"89"}},"gap":"no","elementId":"guten-gsg4hi","heightControl":"min","overflow":"hidden","background":{"videoPlayOnMobile":false,"type":"default","image":{"Desktop":{"id":1730,"image":"' . esc_url( SOVY_URI ) . 'assets/img/guests-waiting.webp"}},"position":{"Desktop":"center center","Tablet":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"theme-4"}},"opacity":"0.9","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"200","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"200","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="gsg4hi"><section class="wp-block-gutenverse-section guten-element guten-section guten-gsg4hi layout-boxed align-stretch overflow-hidden"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-8dDRVB"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-8dDRVB"><div class="guten-column-wrapper" data-id="8dDRVB"><!-- wp:gutenverse/image {"elementId":"guten-vTgWyR","imgSrc":{"media":{"imageId":1731,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( SOVY_URI ) . 'assets/img/error-page.webp","orientation":"landscape"},"medium":{"height":234,"width":300,"url":"' . esc_url( SOVY_URI ) . 'assets/img/error-page.webp","orientation":"landscape"},"large":{"height":799,"width":1024,"url":"' . esc_url( SOVY_URI ) . 'assets/img/error-page.webp","orientation":"landscape"},"full":{"url":"' . esc_url( SOVY_URI ) . 'assets/img/error-page.webp","height":921,"width":1180,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"%","point":"62"}},"imgBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-vTgWyR"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOVY_URI ) . 'assets/img/error-page.webp" height="921" width="1180"/></div></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/heading {"elementId":"guten-BXFVlp","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"ALXll7","font":{"label":"Raleway","value":"Raleway","type":"google"},"size":{"Desktop":{"point":"29","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"800","transform":"uppercase","spacing":{"Desktop":"0.1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-30","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-BXFVlp">PAGE NOT FOUND</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/button {"elementId":"guten-SgsuEU","content":"Back to Home","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"28","bottom":"16","left":"28"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-2"}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"width":2,"type":"solid","color":{"r":0,"g":0,"b":0,"a":0}}},"buttonBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":2,"color":{"type":"variable","id":"theme-3"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"color":{"type":"variable","id":"theme-1"},"iconColor":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"QiqSBU","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"400"},"hoverTextColor":{"type":"variable","id":"theme-3"}} -->
<div class="guten-element guten-button-wrapper guten-SgsuEU"><a class="guten-button guten-button-sm" href="#"><span>Back to Home</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
