<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sovy Home Gutenverse CTA Alt', 'sovy' ),
	'categories' => array( 'sovy-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1295"},"height":{"Desktop":{"point":"543","unit":"px"},"Tablet":{"point":"0","unit":"px"},"Mobile":{"unit":"vh","point":""}},"gap":"no","elementId":"guten-EjFmng","heightControl":"min","align":"middle","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","image":{"Desktop":{"id":388,"image":"https://designer.gutenverse.com/sovy/wp-content/uploads/sites/79/2024/10/interior-view.webp"},"Tablet":[]},"position":{"Desktop":"center center","Tablet":"center center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"size":{"Desktop":"cover","Tablet":"cover"},"fixed":{"Desktop":true,"Mobile":false}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(0, 0, 0, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(11, 19, 21, 0.51)","opacity":0.51,"active":false,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"90"},"opacity":"0.88","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"60","right":"20","bottom":"60","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"80","right":"20","bottom":"80","left":"20"}}}} -->
<div class="section-wrapper" data-id="EjFmng"><section class="wp-block-gutenverse-section guten-element guten-section guten-EjFmng layout-boxed align-middle"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-GpAjn1","horizontalAlign":{"Desktop":"default","Tablet":"center"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"100","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"100","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GpAjn1"><div class="guten-column-wrapper" data-id="GpAjn1"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-fzTBN5","alignText":{"Tablet":"flex-start"},"text":"Reserve","focusText":"","subText":"Reserve A Table","lineWidth":{"Desktop":"9","Mobile":"23"},"lineHeight":{"Desktop":"2"},"lineMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"20","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"mainColor":{"type":"variable","id":"theme-2"},"mainTypography":{"type":"variable","id":"PM6GMF","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"500","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"transform":"uppercase","spacing":{"Desktop":"1"}},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"mainPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"focusMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"focusPadding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"subColor":{"type":"variable","id":"theme-0"},"subTypography":{"type":"variable","id":"1dcJQ2","font":{"label":"Raleway","value":"Raleway","type":"google"},"size":{"Desktop":{"point":"56","unit":"px"}},"weight":"800","transform":"capitalize","lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"subPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"lineColor":{"type":"variable","id":"theme-2"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"35","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"positioningType":{"Mobile":"full"}} -->
<div class="guten-element guten-advanced-heading guten-fzTBN5"><div class="heading-section "><div class="heading-line before"></div><h2 class="heading-title"><span class="heading-title">Reserve</span><span class="heading-focus"></span></h2></div><span class="heading-subtitle">Reserve A Table</span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-kSsHZb","textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"9lek3I","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"%","point":""}}} -->
<div class="guten-element gutenverse-text-editor guten-kSsHZb"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"sectionVerticalAlign":"center","elementId":"guten-FqtU7w","horizontalAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-FqtU7w"><div class="guten-column-wrapper" data-id="FqtU7w"><!-- wp:gutenverse/button {"elementId":"guten-8Eq2CC","content":"Make a Reservation","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"32","bottom":"16","left":"32"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-2"}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"width":2,"type":"solid","color":{"r":0,"g":0,"b":0,"a":0}}},"buttonBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":2,"color":{"type":"variable","id":"theme-3"}}},"color":{"type":"variable","id":"theme-1"},"iconColor":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"QiqSBU","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"400"},"hoverTextColor":{"type":"variable","id":"theme-3"}} -->
<div class="guten-element guten-button-wrapper guten-8Eq2CC"><a class="guten-button guten-button-sm" href="#"><span>Make a Reservation</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '[{"name":"interior-view.webp","image_url":"https:\/\/designer.gutenverse.com\/sovy\/wp-content\/uploads\/sites\/79\/2024\/10\/interior-view.webp","type":"sync","id":2184,"image_id":388}]',
	'is_sync' => true,
);
