<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sovy Gutenverse Contact', 'sovy' ),
	'categories' => array( 'sovy-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1295"},"gap":"no","elementId":"guten-oHpbOo","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-4"}},"border":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":1,"color":{"r":248,"g":248,"b":248,"a":0.05}}},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"20","bottom":"100","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"100","bottom":"80","right":"20","left":"20"}}}} -->
<div class="section-wrapper" data-id="oHpbOo"><section class="wp-block-gutenverse-section guten-element guten-section guten-oHpbOo layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-IRMHKI","horizontalAlign":{"Desktop":"space-between","Mobile":"center"},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"25","bottom":"0","left":"25"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-IRMHKI"><div class="guten-column-wrapper" data-id="IRMHKI"><!-- wp:gutenverse/icon-box {"elementId":"guten-6cYPb7","separateButtonLink":false,"title":"Sovy Restaurant, Jl. Raya \u003cbr\u003eCanggu, Badung, Bali.","titleTag":"span","description":"","icon":"gtn gtn-map-light","iconPosition":"left","align":{"Desktop":"flex-start","Mobile":null},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-2"},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleColor":{"type":"variable","id":"theme-3"},"titleHoverColor":{"type":"variable","id":"theme-3"},"titleTypography":{"type":"variable","id":"9lek3I","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"positioningType":{"Desktop":"inline","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Tablet":{"unit":"%","point":"45"}},"parentSelector":".guten-6cYPb7:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-6cYPb7 guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-map-light"></i></div></div><div class="icon-box icon-box-body"><span class="title">Sovy Restaurant, Jl. Raya <br>Canggu, Badung, Bali.</span></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-xLy4Vv","separateButtonLink":false,"title":"(+62) 81 224 557 900\u003cbr\u003e(+62) 82 222 577 912","titleTag":"span","description":"","icon":"gtn gtn-phone-call-light","iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-2"},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleColor":{"type":"variable","id":"theme-3"},"titleHoverColor":{"type":"variable","id":"theme-3"},"titleTypography":{"type":"variable","id":"9lek3I","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"positioningType":{"Desktop":"inline","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Tablet":{"unit":"%","point":"45"}},"parentSelector":".guten-xLy4Vv:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-xLy4Vv guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-phone-call-light"></i></div></div><div class="icon-box icon-box-body"><span class="title">(+62) 81 224 557 900<br>(+62) 82 222 577 912</span></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-IVXAdM","separateButtonLink":false,"title":"\u003cp style=\u0022margin-right: 0px; margin-left: 0px; transition: 0.4s; color: var( \u002d\u002de-global-color-03dcd93 ); font-size: 16px;\u0022\u003e\u003c/p\u003eReservation@sovy.com\u003cbr\u003eBooks@sovy.com","titleTag":"span","description":"","icon":"gtn gtn-mail-light","iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-2"},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleColor":{"type":"variable","id":"theme-3"},"titleHoverColor":{"type":"variable","id":"theme-3"},"titleTypography":{"type":"variable","id":"9lek3I","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"positioningType":{"Desktop":"inline","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Tablet":{"unit":"%","point":"45"}},"parentSelector":".guten-IVXAdM:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-IVXAdM guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-mail-light"></i></div></div><div class="icon-box icon-box-body"><span class="title"><p style="margin-right: 0px; margin-left: 0px; transition: 0.4s; color: var( --e-global-color-03dcd93 ); font-size: 16px;"></p>Reservation@sovy.com<br>Books@sovy.com</span></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-00Q3jE","separateButtonLink":false,"title":"\u003cp style=\u0022margin-right: 0px; margin-left: 0px; transition: 0.4s; color: var( \u002d\u002de-global-color-03dcd93 ); font-size: 16px;\u0022\u003e\u003c/p\u003eOpen 04:00 pm WITA\u003cbr\u003eClosed 01:00 am WITA","titleTag":"span","description":"","icon":"gtn gtn-clock2-light","iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderResponsive":{"Tablet":{"radius":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-2"},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleColor":{"type":"variable","id":"theme-3"},"titleHoverColor":{"type":"variable","id":"theme-3"},"titleTypography":{"type":"variable","id":"9lek3I","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Tablet":{"unit":"%","point":"45"}},"parentSelector":".guten-00Q3jE:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-00Q3jE guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-clock2-light"></i></div></div><div class="icon-box icon-box-body"><span class="title"><p style="margin-right: 0px; margin-left: 0px; transition: 0.4s; color: var( --e-global-color-03dcd93 ); font-size: 16px;"></p>Open 04:00 pm WITA<br>Closed 01:00 am WITA</span></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => true,
);
