<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sovy Reservation Gutenverse CTA', 'sovy' ),
	'categories' => array( 'sovy-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1295"},"height":{"Desktop":{"point":"543","unit":"px"},"Tablet":{"point":"543","unit":"px"},"Mobile":{"unit":"px","point":"543"}},"gap":"no","elementId":"guten-bQ56vj","heightControl":"min","align":"middle","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","image":{"Desktop":{"id":388,"image":"https://designer.gutenverse.com/sovy/wp-content/uploads/sites/79/2024/10/interior-view.webp"},"Tablet":[]},"position":{"Desktop":"center center","Tablet":"center center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"size":{"Desktop":"cover","Tablet":"cover"},"fixed":{"Desktop":true}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(0, 0, 0, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(11, 19, 21, 0.51)","opacity":0.51,"active":false,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"90"},"opacity":"0.88","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}}} -->
<div class="section-wrapper" data-id="bQ56vj"><section class="wp-block-gutenverse-section guten-element guten-section guten-bQ56vj layout-boxed align-middle"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-rOD2IM","horizontalAlign":{"Desktop":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-rOD2IM"><div class="guten-column-wrapper" data-id="rOD2IM"><!-- wp:gutenverse/divider {"elementId":"guten-oT7O3n","width":{"Desktop":"100","Tablet":"100"},"content":"text","dividerColor":{"type":"variable","id":"theme-2"},"text":"Any Question ?","contentColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"PM6GMF","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"500","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px","point":""}},"transform":"uppercase","spacing":{"Desktop":"0.2","Tablet":"0.18"}},"dividerAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"25","left":"0"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"220","unit":"px"},"Tablet":{"point":"250","unit":"px"}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-oT7O3n"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div><span class="guten-divider-content"><span>Any Question ?</span></span><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/heading {"elementId":"guten-3UlcVE","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"MIyHzu","font":{"label":"Raleway","value":"Raleway","type":"google"},"size":{"Mobile":{"point":"40","unit":"px"},"Desktop":{"point":"85","unit":"px"}},"lineHeight":{"Mobile":{"unit":"em","point":""},"Desktop":{"unit":"em","point":"1.2"}},"weight":"800","transform":"capitalize"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"default","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"657","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-3UlcVE">Stay Close with Us</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/button {"elementId":"guten-7aeWvX","content":"Contact US","buttonWidth":{"Mobile":""},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"28","bottom":"16","left":"28"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-2"}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"width":2,"type":"solid","color":{"r":0,"g":0,"b":0,"a":0}}},"buttonBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":2,"color":{"type":"variable","id":"theme-3"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"theme-1"},"iconColor":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"QiqSBU","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"400"},"hoverTextColor":{"type":"variable","id":"theme-3"}} -->
<div class="guten-element guten-button-wrapper guten-7aeWvX"><a class="guten-button guten-button-sm" href="#"><span>Contact US</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '[{"name":"interior-view.webp","image_url":"https:\/\/designer.gutenverse.com\/sovy\/wp-content\/uploads\/sites\/79\/2024\/10\/interior-view.webp","type":"sync","id":2238,"image_id":388}]',
	'is_sync' => true,
);
