export { default as Home } from './Home'
export { default as MenuPage } from './MenuPage'
export { default as WinesPage } from './WinesPage'
export { default as Admin } from './Admin'
export { default as NotFound } from './NotFound'
